
package:
  name: cinema4d-plugin-bundle
  version: "1.0"

source:
- path: ../../archive_files/cinema4d-plugin-bundle/win-64 # [win64]

build:
  number: 0
  # noarch: generic
  binary_relocation: false
  detect_binary_files_with_prefix: false
  ignore_prefix_files: true
  missing_dso_whitelist:
    - "**"

requirements:
  run:
    - cinema4d >=2025

about:
  license: LicenseRef-Multiple
