
package:
  name: cinema4d-plugin-bundle
  version: "1.0"

source:
- path: ../../archive_files/cinema4d-plugin-bundle/win-64 # [win64]


build:
  script_env:
    - CONDA_BUILD_SKIP_ACTIVATE=1
  noarch: generic
  # script: |
  #   set "C4D_PLUGINS_DIRECTORY=%PREFIX%\cinema4d\Plug-ins"
  #   mkdir "%C4D_PLUGINS_DIRECTORY%"
  #   robocopy "%SRC_DIR%" "%C4D_PLUGINS_DIRECTORY%" /E /NFL /NDL /NJH /NP

# build:
#   script: echo "no build"
#   number: 0
#   binary_relocation: False
#   detect_binary_files_with_prefix: False
#   missing_dso_whitelist:
#   - "**"
  
# requirements:
#   host:
#     - python
#   # run:
#   #   - cinema4d

about:
  license: LicenseRef-Multiple
